os: linux

language: php

jobs:
  fast_finish: true
  include:
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      dist: bionic
  allow_failures:
    - php: nightly

services:
  - redis

before_install:
  - travis_retry composer self-update

install: travis_retry composer install --no-interaction --prefer-source --no-suggest

script: vendor/bin/phpunit
