language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly

services:
  - redis-server

before_install:
  - travis_retry composer self-update

install: travis_retry composer install --no-interaction --prefer-source --no-suggest

script: vendor/bin/phpunit
